### ISSUE TITLE
"npm install" fail on Node v0.12.0

### ISSUE THREAD

**Issue by mahiuchun** [BYVoid/opencc-web#1]
error log:
http://paste.ubuntu.com/10655321/

My OS is OS X 10.10.2 with Node installed by "brew install node"

**Comment by Fenzland** [comment]
With node 8.4.0 failed too.
```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at _errnoException (util.js:1041:11)
gyp ERR! stack     at TLSWrap.onread (net.js:606:25)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "$pathToNode/nodejs/bin/node" "$pathToNode/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd ~/web/opencc-web/node_modules/opencc
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencc@1.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
```
